Fix nil pointer dereference
newscred/webhook-broker pull request #195
Opened 2024-12-19 11:56 UTC by MunifTanjim

TICKET: https://jira.sso.episerver.net/browse/<TICKET-ID>

Related PRs:
- ...

## Description

## QA Steps

- [ ]

2024-12-19 12:36 UTC, syednabilashraf approved these changes

2024-12-19 12:36 UTC, syednabilashraf approved these changes

2024-12-19 13:31 UTC, imyousuf requested changes
Need test cases please.

2024-12-30 17:21 UTC, imyousuf approved these changes

2024-12-30 17:21 UTC, merged